### ISSUE TITLE
[交互建议] 增加Windows系统托盘最小化运行，和退出二次确认逻辑

### ISSUE THREAD

**Issue by yeyuan520** [NonebotGUI/nonebot-flutter-gui#14]
### 问题
目前版本的NBGUI点击窗口×键将直接结束运行程序，非常容易造成**误触**。其次，作为一个机器人程序长期挂机是必要的，但是目前nbgui并没有做**托盘处理**，最小化程序则会占用任务栏一格图标这非常不美观。

### 建议
1.增加托盘运行功能，最小化程序时，默认以Windows托盘模式运行。
2.点击窗口x键进行二次确认，给予用户三个选项。 大概如下

=您是否要退出本程序    ？       =
=                                                =
= 是（Y） 否（N）最小化运行 =
=====================
点击最小化运行则就是托盘模式，望采纳。

**Comment by XTxiaoting14332** [comment]
Done
