### ISSUE TITLE
README未更新 一个小问题

### ISSUE THREAD

**Issue by qllokirin** [NonebotGUI/nonebot-flutter-gui#19]
20行的`#使用截图`应替换为`#%EF%B8%8F-使用截图`

https://github.com/NonebotGUI/nonebot-flutter-gui/blob/1bd64de17deacf62c422f44cfba5ebdef4269274/README.md?plain=1#L20

看起来是因为加了个表情导致跳转不了了

**Comment by XTxiaoting14332** [comment]
已修正 谢谢提醒
