### ISSUE TITLE
[suggest]日志优化

### ISSUE THREAD

**Issue by hlfzsi** [NonebotGUI/nonebot-flutter-gui#23]
众所周知，nb的日志十分冗长（）。当前，尝试使用滚轮向上查看控制台输出时，控制台输出会自动下翻，和滚轮抢控制权。每一次都去打开日志文件找对应日志真的相当麻烦。
此外，错误日志的提示可能需要优化。jieba初始化和设置环境变量以及刷新token等操作均会导致错误日志产生反应。此外，我认为应当放弃在gui中打开日志，而是直接使用记事本打开，这有助于提高gui稳定性，防止莫名其妙卡死。

还有一些和本issue主题无关的碎碎念：
gui包含了协议端部署，这很方便。但作为nb的gui，我认为应当更多倾向nb自身。譬如：直接在gui中修改env，提示一些env中常用的常量。
gui应当小巧轻量。这一点目前我认为在及格线以上。考虑到机器人大部分的运行环境都是极度低配的，gui不能也无法占用过多资源，只专注于核心功能而抛弃与nb无关的或关系相对小的功能是一个好办法。如果有精力，可以考虑插件化的开发，由用户自行选择需要安装的功能。

如果我说的有所有偏颇，还请谅解

**Comment by XTxiaoting14332** [comment]
感谢反馈 
首先 滚轮的问题将会在下个版本中得到修复
错误日志是由 dart 的 `process` 进行捕获，所以错误日志暂时还修不了
env编辑在正在设计实现方案，将会在后续加上
关于插件化开发，本人为苦逼高三生（） 没有过多的精力去进行插件化开发（ 如果希望减少占用可以关注正在开发的 `nonebot-flutter-webui` 项目

**Comment by XTxiaoting14332** [comment]
Done

**Comment by Muska-Ami** [comment]
其实GUI的占用并不高吧...

**Comment by XTxiaoting14332** [comment]
> 其实GUI的占用并不高吧...

有时候会忽然内存溢出

**Comment by Muska-Ami** [comment]
> > 其实GUI的占用并不高吧...
> 
> 有时候会忽然内存溢出

用好你的 `dispose()`

**Comment by XTxiaoting14332** [comment]
> > > 其实GUI的占用并不高吧...
> > 
> > 有时候会忽然内存溢出
> 
> 用好你的 `dispose()`

我明天检查看看还有哪里没dispose
